//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ShopManagementSystem.Models;
using System.Collections.Generic;
using System.Web;
public class Shoppack
{
    public Shoppack()
    {
        this.category = new Category();
        this.person = new Login();
        this.customer = new Customer();
        this.package = new Package();
        this.package1 = new Package();
        this.shop = new Shop();
        this.shopKeeper = new ShopKeeper();
        this.item = new Item();
        this.picture = new Picture();
        this.saved = new Saved();

    }
    public Category category { get; set; }
    public Login person { get; set; }
    public Customer customer { get; set; }
    public Package package { get; set; }
    public Package package1 { get; set; }
    public Picture picture { get; set; }
    public Shop shop { get; set; }
    public ShopKeeper shopKeeper { get; set; }

    public Saved saved { get; set; }

    public Item item { get; set; }

    public List<Category> categorylist { get; set; }

    public List<Item> itemlist { get; set; }

    public List<Picture> picturelist { get; set; }

    public List<Saved> savelist { get; set; }




}



public class ItemPicture
{
    public Item item { get; set; }
    public Picture picture1 { get; set; }

    public Picture picture2 { get; set; }

    public Picture picture3 { get; set; }

    public Picture picture4 { get; set; }

    public Picture picture5 { get; set; }


    public List<Item> itemlist { get; set; }
    public List<Picture> picturelist { get; set; }

}


