//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Saveds = new HashSet<Saved>();
            this.Orders = new HashSet<Order>();
        }
    
        public int LoginId { get; set; }

       
        public string Address { get; set; }
    
        public virtual ICollection<Saved> Saveds { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Login Login { get; set; }
    }
}
