//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Item
    {
        public Item()
        {
            this.Saveds = new HashSet<Saved>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Pictures = new HashSet<Picture>();
        }
    
        public int Id { get; set; }

        [Required]
        [DataType(DataType.Text)]
        
        public string Name { get; set; }

        public string Description { get; set; }
        public bool Available { get; set; }
        public bool ComingSoon { get; set; }
        public int CategoryId { get; set; }
        [Required]
        [DataType(DataType.Currency)]
        public int Price { get; set; }

        [Display(Name = "Quantity")]
        [RegularExpression("^[0-9]", ErrorMessage = "Invalid Quantity")]
        [Range(1, 9999999, ErrorMessage = "Quantity can never be a negative")]
        public int Quantity { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Saved> Saveds { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
    }
}
