//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.orderdate = OrderDate;
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int ShopID { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        DateTime orderdate = DateTime.Now;

       
        public System.DateTime OrderDate { get; set; }
        public string Track { get; set; }
        public bool Paypal { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
