//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class OrderDetail
    {
        public int OrderId { get; set; }
        public int ItemId { get; set; }

        [Display(Name = "Quantity")]
        [RegularExpression("^[0-9]", ErrorMessage = "Invalid Quantity")]
        [Range(1, 999999, ErrorMessage = "Quantity can never be a negative")]
        public double Quantity { get; set; }
        public int OrderDetailsId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Order Order { get; set; }
    }
}
