//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Package
    {
        public Package()
        {
            this.Shops = new HashSet<Shop>();
            this.Shops1 = new HashSet<Shop>();
        }
    
        public int Id { get; set; }


        [Required]
        [DataType(DataType.Text)]
        
        public string Name { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        public string Price { get; set; }
    
        public virtual ICollection<Shop> Shops { get; set; }
        public virtual ICollection<Shop> Shops1 { get; set; }
    }
}
