//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Picture
    {
        public int Id { get; set; }
        public byte[] picture1 { get; set; }



        public HttpPostedFileBase ImageFile1 { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> ShopID { get; set; }

        public virtual Item Item { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
