//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ShopManagementSystem.Models;
public class Register
{
    public Register()
    {
        this.person = new Login();
        this.customer = new Customer();
        


    }
    public Login person { get; set; }
    public Customer customer { get; set; }
    

}

