
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Shop
    {
        public Shop()
        {
            this.Categories = new HashSet<Category>();
            this.Orders = new HashSet<Order>();
            this.Pictures = new HashSet<Picture>();
            this.ShopKeepers = new HashSet<ShopKeeper>();
            this.pstart = PStart;
            this.pend = PEnd;
        }
    
        public int Id { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Name { get; set; }

        [Required]      
        public string Description { get; set; }
        public int SubPackage { get; set; }
        public Nullable<int> AppPackage { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        DateTime pstart = DateTime.Now;
        

        public System.DateTime PStart { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        DateTime pend = DateTime.Now.AddYears(2);
        public System.DateTime PEnd { get; set; }

        public string Address { get; set; }
        [Required]
        [DataType(DataType.PhoneNumber)]
        public string Contact { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Package Package { get; set; }
        public virtual Package Package1 { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
        public virtual ICollection<ShopKeeper> ShopKeepers { get; set; }
    }
}
